name: GMPaidRanks
main: com.palmergames.GMPayRanks.GMPayRanks
version: 1.3
authors: [polaris120990,ElgarL]
description: >
             Ranks a player up for money.
softdepend: [GroupManager,iConomy,Register,Vault]
commands:
   rankup:
      description: Ranks you up if you can afford it.
