name: PaidRanks
main: me.polaris120990.PayRanks.PayRanks
version: 1.0d
author: polaris120990
description: >
             Ranks a player up for money.
softdepend: [GroupManager,iConomy]
commands:
   rankup:
      description: Ranks you up if you can afford it.
